### PR TITLE
Graylog master auto selection for kubernetes/openshift statefulset

### PR DESCRIPTION
**Pull request by pastukhov**

### CODE REVIEW

**Comment by jalogisch** [comment]
grafik

**Comment by jalogisch** [comment]
Do you mind @pastukhov to document that behavior over in the documentation? 

https://github.com/Graylog2/documentation/blob/2.5/pages/installation/docker.rst

That would help people to use that function when it is merged - when the documentation is given I'll merge that.

**Comment by pastukhov** [comment]
@jalogisch Good idea. I will make it today.

**Comment by pastukhov** [comment]
@jalogisch https://github.com/Graylog2/documentation/pull/546

**Comment by jalogisch** [comment]
I'll merge that and hope that you @pastukhov update the documentation pr because that needs some love.

Thank you.

**Pull request merged**
