### PR TITLE
Improve kubernetes secret support

### PR DESCRIPTION
**Pull request by runningman84**
In kubernetes you store parameters like usernames and passwords in kubernetes secrets. These secrets can be loaded into the environment:
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
This pull request made it possible to configure the container like this:
https://github.com/arvatoaws/graylog-helm-chart/blob/master/graylog/templates/graylog-master.yaml

### CODE REVIEW

**Comment by runningman84** [comment]
@bernd what do you think about this pull request?

**Comment by jalogisch** [comment]
as written via mail @runningman84 once you provide a documentation that describes how others can use that - similar to what can be found here: http://docs.graylog.org/en/3.0/pages/installation/docker.html#kubernetes-automatic-master-selection

I'm happy to merge your change.

**Comment by pastukhov** [comment]
IMHO it just add excessive complexity.
Why just not create config map with correct env vars. Something like this:
```
{{- $elasticsearchServiceName := include "elasticsearch.fullname" . -}}
{{- $externalProtocol := include "graylog.ingress.externalProtocol" . -}}
{{- $externalDomain := include "graylog.ingress.externalDomain" . -}}
{{- $graylogServiceName := include "graylog.fullname" . -}}
{{- $mongodbServiceName := include "mongodb.fullname" . -}}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "graylog.fullname" . }}-configmap
  labels:
    configVersion: v1
    app: {{ template "graylog.fullname" . }}
    chart: {{ template "graylog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  GRAYLOG_ELASTICSEARCH_HOSTS: "http://{{ .Release.Name }}-elasticsearch-client:9200"
  GRAYLOG_WEB_LISTEN_URI: "http://0.0.0.0:9000/"
  GRAYLOG_WEB_ENDPOINT_URI: "{{ $externalProtocol }}://{{ .Release.Name }}.{{ $externalDomain }}/api"
  GRAYLOG_REST_LISTEN_URI: "http://0.0.0.0:9000/api/"
  GRAYLOG_SERVER_JAVA_OPTS: "-Xms2g -Xmx2g -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"
  GRAYLOG_MONGODB_URI: "mongodb://{{ $mongodbServiceName }}-0.{{ $mongodbServiceName }}:27017,{{ $mongodbServiceName }}-1.{{ $mongodbServiceName }}:27017,{{ $mongodbServiceName }}-2.{{ $mongodbServiceName }}:27017/graylog?replicaSet=rs0"
  GRAYLOG_METRICS_PROMETHEUS_ENABLED: "false"
```
and  add to deployment something like this:
```
          envFrom:
          - configMapRef:
              name: {{ template "graylog.fullname" . }}-configmap

```

**Comment by jalogisch** [comment]
that is a nice idea @pastukhov - I prefer simplicity and taking already given structure over the need to create something new.

I'm not into kubernetes - do we need to add something to the image for that solution?

**Comment by pastukhov** [comment]
I don't think so, but someone can have another opinion.

**Comment by OskarFromSpain** [comment]
the problem is, that the configmaps resulting with some issues with the latest docker image.

See below:
adding environment opts
chown: changing ownership of '/usr/share/graylog/data/journal': Operation not permitted

It cant change owner permission of readonly configmaps configurations.
(https://github.com/Graylog2/graylog-docker/issues/62)

The error is handled here, but it still coming up with the image graylog/graylog:3.0.0-1.

**Comment by pastukhov** [comment]
You don't need to mount configmap in to pod. Just do
```
          envFrom:
          - configMapRef:
              name: {{ template "graylog.fullname" . }}-configmap
``` 
for graylog pod.
data/journal is not configmap. As i know it is state for a pod. It should be located on PV, and it is a problem for current docker entrypoint.

**Comment by runningman84** [comment]
@pastukhov in your configmap example how do you pass the a secret into the configmap?

Secrets like MONGODB_USERNAME and MONGODB_PASSWORD are not definied in the helm chart but auto generated using kubedb and need to be imported using "valueFrom: secretKeyRef:"

**Comment by pastukhov** [comment]
@runningman84 You are right
All the passwords are in the secret:
```
          envFrom:
          - configMapRef:
              name: {{ template "graylog.fullname" . }}-configmap
          - secretRef:
              name: {{ template "graylog.fullname" . }}-secrets
```

**Comment by runningman84** [comment]
@pastukhov but the problem is that you have to construct the mongodb uri and elasticsearch uri with data from the secrets. I do not see how your solution would solve this.

**Comment by pastukhov** [comment]
Just keep full elastic/mongo url in the secret and utilize it as envFrom

**Comment by runningman84** [comment]
@pastukhov this is the point... you cannot keep the full url because kubedb provides the username and password and other values as a single secret.

**Comment by pastukhov** [comment]
Ok, then you always can add init container/custom docker-entrypoint.sh that should extract security sensitive data from kubernetes secret/terraform vault/whatever and construct proper url.
Hardcode this logic with variables defined at your taste to common entry point isn't good idea IMHO.

**Comment by juju2112** [comment]
Closing this out as there's been no discussion on it in over a year.

**Pull request closed without merging**
