### PR TITLE
Set GRAYLOG_IS_MASTER if hostname matches

### PR DESCRIPTION
**Pull request by runningman84**
This will make graylog deployments in kubernetes alot easier...

Right now we have to define master and slave nodes in two stateful sets:
https://github.com/arvatoaws/graylog-helm-chart/blob/master/graylog/templates/graylog-master.yaml
https://github.com/arvatoaws/graylog-helm-chart/blob/master/graylog/templates/graylog-slave.yaml

We could combine them in one template with this fix.

This is my test script:
```
#!/bin/bash

export GRAYLOG_IS_MASTER=false

echo master hostname
echo $GRAYLOG_SERVER_MASTER_HOSTNAME
echo hostname
echo $HOSTNAME

# enable master flag if hostname matches
if [ "$GRAYLOG_SERVER_MASTER_HOSTNAME" == "$HOSTNAME" ]; then
  export GRAYLOG_IS_MASTER=true
fi

echo $GRAYLOG_IS_MASTER
```

### CODE REVIEW

**Comment by runningman84** [comment]
Feel free to integrate it in #54. Unless we get some auto election of master servers this is the best solution to get a simple stateful deployment.

**Comment by runningman84** [comment]
@jalogisch #54 is already merged, what do you want to do with this pull request?

**Comment by jalogisch** [comment]
@runningman84 we do not have a strong opinion on that currently. We do not run Openshift and Kubernetes environments or have strong knowledge about the best practice. 

We will discuss this topic.

**Comment by runningman84** [comment]
@pastukhov that's a great solution for kubernetes only deployments but might break the general docker usage outside of kubernetes....

**Comment by pastukhov** [comment]
Check for $POD_NAME can be added. POD_NAME is kubernetes only thing.

**Comment by runningman84** [comment]
@pastukhov would you mind creating a pull request for this?

**Comment by pastukhov** [comment]
@runningman84 https://github.com/Graylog2/graylog-docker/pull/60

**Comment by jalogisch** [comment]
I'll close this PR now as we have https://github.com/Graylog2/graylog-docker/pull/60 merged and new images are already built with that included.

**Pull request closed without merging**
