### PR TITLE
Update to Java 17 and retire Java 11 tagged images

### PR DESCRIPTION
**Pull request by mpfz0r**
## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

### CODE REVIEW

**Comment by coffee-squirrel** [comment]
With `8` and `11` dropped there could be some minor cleanup in `docker-entrypoint.sh`.  `UseParNewGC` was removed in `10` and `UseConcMarkSweepGC` was removed in `14`.

https://github.com/Graylog2/graylog-docker/blob/5.0/docker-entrypoint.sh#L11-L22

**Comment by mpfz0r** [comment]
Thanks for the reminder @coffee-squirrel :+1: Much appreciated!

**Comment by mpfz0r** [comment]
Refs: https://github.com/Graylog2/graylog-plugin-enterprise/issues/3997

**Comment by mpfz0r** [comment]
This has been superseded by other commits.
The last missing part was moved to https://github.com/Graylog2/graylog-docker/pull/227

**Pull request closed without merging**
