### PR TITLE
this can be a fix for #36 and #38

### PR DESCRIPTION
**Pull request by bodsch**
**but needs test in an openshift / kubernetes environment**

### CODE REVIEW

**Comment by theSuess** [comment]
I've managed to get this running on Openshift but had to apply some changes:

Added this to the dockerfile
```
chgrp -R 0 ${GRAYLOG_HOME} && \
chmod -R g=u ${GRAYLOG_HOME} && \
```
And removed this line in the entrypoint script
`chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" "${GRAYLOG_HOME}/data"`

**Comment by bodsch** [comment]
@theSuess 
Thanks for your test!
Where did you place your changes in the `Dockerfile`?

**Comment by theSuess** [comment]
Right below
```
chown --recursive "${GRAYLOG_USER}":"${GRAYLOG_GROUP}" ${GRAYLOG_HOME} && \
```
and before 
```
setcap 'cap_net_bind_service=+ep' "${JAVA_HOME}/bin/java" && \ 
```

**Comment by jalogisch** [comment]
@bodsch if you can resolve the conflicts I'll merge this into 2.4 and would wait for a PR for 2.5 and 3.0 branch.

thank you for your help

**Comment by jalogisch** [comment]
@bodsch will you port them to 2.5 and 3.0 ?

**Comment by jalogisch** [comment]
just for reference - this is already in 2.5 and 3.0

**Pull request merged**
